### ISSUE TITLE
Attempt to call field 'get_at' (a nil value) when building an android game

### ISSUE THREAD

**Issue by Fossean1** [selimanac/defold-astar#5]
When I try to build the project on my mobile android device, I get this message: `attempt to call field 'get_at' (a nil value)`. No such problem when building on Windows

**Comment by selimanac** [comment]
Lib doesn't contain any platform specific code, so it should be same. 
There might be another problem related to your setup. Are you sure the tiles set correctly? Is there any other error messages?

**Comment by selimanac** [comment]
I'm going to close this since there is not enough info.
